### ISSUE TITLE
Enumerable argument type?

### ISSUE THREAD

**Issue by SuperJMN** [j-maly/CommandLineParser#13]
Is it possible to define an argument that accepts a list of values? Something like:

command.exe --reportTypes 1 4 5

Thanks!

**Comment by hdsler** [comment]
Same question

**Comment by j-maly** [comment]
Hi, it is possible, somewhat.. 

You can combine 1) equals sign syntax + 2) AllowMultiple = true

```
commandLineParser.AcceptEqualSignSyntaxForValueArguments = true;
ValueArgument<int> lines = new ValueArgument<int>('r', "reportTypes", "Report types") { AllowMultiple = true };
```

This will allow this format: 
--reportTypes=1,4,5

Or you can achieve something similar with "additional arguments" - see https://github.com/j-maly/CommandLineParser/wiki/Command-line-format - Additional Arguments section

**Comment by hdsler** [comment]
Thanks. Gonna try aproach from 

> https://github.com/j-maly/CommandLineParser/wiki/Command-line-format - Additional Arguments section
