### ISSUE TITLE
Impossible to override CertifiedValueArgument.Certify

### ISSUE THREAD

**Issue by heribo** [j-maly/CommandLineParser#17]
Certify is declared `internal` in `CertifiedValueArgument`, so it's not possible to extend the library by creating custom argument types as described in the documentation (in `RegexCertifiedArgument`)

Could you please remove the `internal` attribute?

**Comment by j-maly** [comment]
Hi, thanks for reporting this, I'll remove it asap.

**Comment by j-maly** [comment]
The fix is avail in new version of the nuget package https://www.nuget.org/packages/CommandLineArgumentsParser/3.0.3 

If you have an idea for a reusable argument type, pull requests are welcome.
