### ISSUE TITLE
how can i parse params like "dosomething.exe aaa --disable-background"

### ISSUE THREAD

**Issue by ysunf** [j-maly/CommandLineParser#20]
i can see the usage for params with short name or long name, but how about the params without names? For example, the chrome, startup with "chrome.exe www.bing.com --disable-background-networking" or maybe "chrome.exe --disable-background-networking www.bing.com --disable-component-update"? Thanks for your help!

**Comment by j-maly** [comment]
Unfortunately, this is not supported.

**Comment by j-maly** [comment]
Closing as this is a duplicate of #18
