### ISSUE TITLE
SwitchArgument does not set parser field (version 3.0.4)

### ISSUE THREAD

**Issue by DaveRobSwEng** [j-maly/CommandLineParser#21]
I have a parsing target class: 

    [ArgumentGroupCertification("i,r", EArgumentGroupCondition.ExactlyOneUsed)]
    internal class ParsingTarget
    {
        [SwitchArgument('i', "install", true, Description = "Install the tamper file")]
        public bool Install;
    
        [SwitchArgument('r', "remove", false, Description = "Remove the tamper file")]
        public bool Remove;
    
        [ValueArgument(typeof(string), 'e', "exe", Description = "Full path to the exe file", Optional = false)]
        public string ExePath;
    }

With command line `-i -e DummyFile` and parsing code:
    ParsingTarget p = new ParsingTarget();
    parser.ExtractArgumentAttributes(p);
    parser.ParseCommandLine(args);

The p.Install field does not get set to true.

Sample VS2105 solution showing the issue attached.

[TestCmdParser.zip](https://github.com/j-maly/CommandLineParser/files/726884/TestCmdParser.zip)

**Comment by j-maly** [comment]
You've set the default value for "Install" to true. When -i is among the arguments, the parser will switch it to false. 
Maybe you want the default to be false and when -i is among the arguments, it will set p.Install to true? 
In that case, you should declare it as you did your -r argument:
[SwitchArgument('i', "install", false, Description = "Install the tamper file")]
