### ISSUE TITLE
Problems opening solution with Visual Studio 2015

### ISSUE THREAD

**Issue by gojimmypi** [j-maly/CommandLineParser#22]
when attempting to open in Visual Studio 2015, I see several of these errors:

error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.   

indeed I don't even have a DotNet directory, let alone any Microsoft.DotNet.Props files in C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0for VS 2015\

I tried manually commenting the line in the .xproj files, but then Visual Studio just explodes with a "fatal error" message when attempting to open the solution. 

I assume you are using the not-yet-fully released VS2017?  :)

**Comment by j-maly** [comment]
Do you have .NET core SDK installed? (I am using VS 2015 community edition)

**Comment by gojimmypi** [comment]
I am using Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3.

I appear to have 2 .NET core items listed in control panel, installed Dec 2016 / Jan 2017; both are labeled "preview" as shown in screensnip:

![dotnetcore](https://cloud.githubusercontent.com/assets/13059545/22617665/6df899b2-ea7f-11e6-96e9-3c55daddf90e.PNG)

btw - I forked & was able to strip out some stuff & get your code working. It is quite cool. Thanks for posting :)
