### ISSUE TITLE
multiple items not parsed

### ISSUE THREAD

**Issue by utillity** [j-maly/CommandLineParser#27]
this argument will not be correctly filled:

    [ValueArgument(typeof(string), Argument.UnsetShortNameChar, "types", 
      Optional = true, AllowMultiple = true, Description = "The file-types to process")]
    public string[] FileTypes { get; set; }

commandline:
`--types png jpg pdf`

only the first argument (png) is assigned and the other 2 are interpreted as "additional arguments"

**Comment by vwilson317** [comment]
Anyone know if this is fixed?

**Comment by j-maly** [comment]
the format is slighly different, you can use 
--types png --types jpg --types pdf
or 
--types=png,jpg,pdf
or 
--types="png,jpg,pdf"
