### ISSUE TITLE
BoundedValueArgument<int> throws NRE when used as Attribute

### ISSUE THREAD

**Issue by bexxx** [j-maly/CommandLineParser#30]
public class CommandLineArguments
{
        [BoundedValueArgument(typeof(int), 'd', "duration", Description = "The duration of the acoustic data used in the adaptation.", ValueOptional = true, MinValue = 0, DefaultValue = 0)]
        public int Duration { get; set; }
}

Parsing with:

using (var parser = new CommandLineParser())
            {
                var arguments = new CommandLineArguments();
                parser.ExtractArgumentAttributes(arguments);
                parser.ParseCommandLine(args);
            }

throws NRE here:
   at CommandLineParser.Arguments.BoundedValueArgumentAttribute.set_ValueOptional(Boolean value)

**Comment by bexxx** [comment]
When I change to
public static void SetPropertyValue(this Type type, string propertyName, object target, object value)
        {
#if (!(NET40 || NET35 || NET20))
            PropertyInfo property = type.GetProperty(propertyName);
            property.SetValue(target, value);
#else
            type.InvokeMember(propertyName, BindingFlags.SetProperty, null, target, new object[] { value });
#endif
        }

(BoundedArgument does not declare, but inherit the property ValueOptional) in TypeExtensions.cs then it works for me. I could create a pull request, but I do not know your code base very well and I am unsure about the effects of this change.

**Comment by j-maly** [comment]
This should be fixed in 3.0.7
