### ISSUE TITLE
Not  signed

### ISSUE THREAD

**Issue by TheSaltyKorean** [j-maly/CommandLineParser#32]
`warning BC41997: Referenced assembly 'CommandLineArgumentsParser, Version=3.0.7.0, culture=neutral, PublicKeyToken=null' does not have a strong name.`

Could you guys create a .snk file and sign the dll please?

**Comment by j-maly** [comment]
3.0.10 should now be strongly named.

**Comment by TheSaltyKorean** [comment]
`warning BC41997: Referenced assembly 'CommandLineArgumentsParser, Version=3.0.20.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Broken again
