### ISSUE TITLE
How to write out ALL arguments and their values?

### ISSUE THREAD

**Issue by LightTempler** [j-maly/CommandLineParser#33]
Using ShowParsedArguments() it 's very easy to write **parsed** arguments to console.

I'm looking for a similar way to report **everything** my parsingtarget class holds (varnames / values) to console. This can give user an overview of complete set (given parameters, used default values).

After parsing I have access to parsers argument collection, but the PrintValueInfo() method of the args is internal, so a simple loop cannot do the job.

**Comment by j-maly** [comment]
This should be simple to add, I'll take a look.
