### ISSUE TITLE
Missing docu 'multiple values with declarative syntax'

### ISSUE THREAD

**Issue by LightTempler** [j-maly/CommandLineParser#34]
> "If you are using attributes (declarative syntax), you need to use the attribute on an array or list property/field"

Tried it in many ways (array, List<String>, ...) with public var or property. In any case all i got was this error:

_Type System.Collections.Generic.List`1[System.String] of argument 123 is not a built-in type.Set ConvertValueHandler to a conversion routine for this type or define static method Parse(string stringValue, CultureInfo cultureInfo) that can Parse your type from string._

One of my tried defs:

_[ValueArgument(typeof(List<string>), 't', "IDtag", AllowMultiple = true, Description = "desc to ID tags")]
public List<string> SGIDtag { get; set; }_

Called with:

   myapp.exe -t val1 val2
or
   myapp.exe -t "123" "456"

**Comment by j-maly** [comment]
Hi, you should use the type of the item for the typeof, such as 
[ValueArgument(typeof(string), ...)]
Check out ArgumentBoundToCollection_shouldCreateInstanceOfTheCollection in https://github.com/j-maly/CommandLineParser/blob/master/src/Tests/Tests.ValueArgument.cs

**Comment by LightTempler** [comment]
Hi, thx for fast reply!
Now no more errors, but only first value is in list.
I 've checked  ValueArgument.Values  collection, too -> 1 item, but there should be three.
Hiw can I dig deeper into this?

btw: After real live evolving three other "famous" .NET commandline parser libs, I 've decided: Overall yours seems to be the best and I will use it in my projects. Thank you very much for this great piece of work.

**Comment by j-maly** [comment]
Can you post the list of arguments you pass on the command line?

**Comment by LightTempler** [comment]
_myapp.exe -t #abc #xyz #A55_

I got _Count=1_ and  _#abc_  as only value in list.

**Comment by j-maly** [comment]
Yeah, the format is slightly different... and it confuses a lot of people :( 
you can use 
myapp.exe -t #abc -t #xyz -t #A55
or 
myapp.exe -t="#abc,#xyz,#A55" (with equals sign syntax turned on) 
maybe 
myapp.exe -t=#abc,#xyz,#A55 would work too, can't remember from the top of my head...

I am aware that many people would prefer 
myapp.exe -t #abc #xyz #A55
its just that this was against the original requirements which are not that relevant anymore and I never got to changing that...

**Comment by LightTempler** [comment]
All three versions work great, thank you!

Maybe in next update of docu a short note to could help others.
