### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by LightTempler** [j-maly/CommandLineParser#35]
Any chance this powerfull regex argument extension will be implemented with attribute support?
It would extend the early automated validating possibilities alot! GUIDs, email addresses, IP addresses and many more could be done with ...

Your given source example  'RegexCertifiedArgument' works great, but writing an attribute aupport class is far beyond my .NET skills :)

**Comment by j-maly** [comment]
Yes, but I'd need to find another good example for demonstrating extensibility!

**Comment by LightTempler** [comment]
:-) Good argument!

But: After adding regex, the need to extensions has decreased to close to nothing.
And: On evaluating a new tool, programmers really like to get universal use out-of-the-box.

Without attribute support, mapping regex values back into parse clase leads to ugly, not clean code.
So I give you some new example themes in exchange  for a full regex ;-)  :
GUIDs and timespans are easy to validate with buildin parse/tryparse functions and usefull, too. They wouldn't need a lot of changing in example code.
