### ISSUE TITLE
Extend argument for supporting Guid values

### ISSUE THREAD

**Issue by delfuria** [j-maly/CommandLineParser#46]
I tried to extend the library for supporting Guid values.
I have created a GuidArgumentAttribute and a GuidArgument classes following this link
https://github.com/j-maly/CommandLineParser/wiki/Extensibility-&-custom-arguments
but i cannot reach to execute because i get a MissingMethodException.
What has been wrong ?
Thanks

**Comment by j-maly** [comment]
Since Guid was not one of the types supported out of the box by ValueArgument, you would need to override this method: 
public virtual TValue Convert(string stringValue)

But now I've added Guid to ValueArgument directly as you suggested.

**Comment by delfuria** [comment]
Thanks a lot.
