### ISSUE TITLE
Can't override Argument.Parse in my own argument class

### ISSUE THREAD

**Issue by dacendale** [j-maly/CommandLineParser#51]
Looking at the code the virtual Parse method is marked as internal. I can't extend from Argument (or one of its subclasses) and override Parse. This completely negates me from using this library to parse a command line with multiple strings for a single value. For example, if I try to add a convert handler to a ValueArgument it is just passed a single string and I need multiple strings to convert to my value type.

**Comment by j-maly** [comment]
Parse made public in v 3.0.18. Good luck with your project.

**Comment by dacendale** [comment]
Thanks for that incredible response!
