### ISSUE TITLE
Default value for non-existing argument

### ISSUE THREAD

**Issue by YauhenPyl** [j-maly/CommandLineParser#55]
Hello, thank you for the great library.

Is it possible to set different default values for ValueArgument if it is passed but without any value and if it is not passed at all? E.g.
```
internal class Arguments
{
    [ValueArgument(typeof(string), 'a', "argument", ValueOptional = true, DefaultValueNonExisting = "", DefaultValue = null, Optional = true)]
    public string Value { get; set; }
}
```
* Value will be 'Argument':
```
 my-tool.exe -a Argument
```
* Value will be "":
```
my-tool.exe
```
* Value will be 'null':
```
my-tool.exe -a
```

Thanks

**Comment by j-maly** [comment]
Hi, it could be added but I can't give you any ETA atm. If you don't want to implement it yourself... 

As a workaround, you could 
 - not specify DefaultValue 
 - after parsing the commandline, check the Parsed property of your argument and correct the value based on that

**Comment by eapyl** [comment]
Added quick implementation for this idea.

**Comment by alexandre-lecoq** [comment]
This was implemented. Issue can be closed.
