### ISSUE TITLE
EnumeratedValueArgument w/ Enum

### ISSUE THREAD

**Issue by Kritner** [j-maly/CommandLineParser#56]
At a glance, I'm not seeing a method of using an `enum` along with `EnumeratedValueArgument`, specifically when using a attribute style parsing target.

I was hoping for something like:

```
        public enum MyEnum
        {
            One,
            Two
        }

        [EnumeratedValueArgument(typeof(MyEnum), 'm', "myEnum")]
        public MyEnum ParsedEnum;
```

or perhaps:
```
public enum MyEnum
        {
            One,
            Two
        }

        public static Dictionary<MyEnum, string> EnumMapping = new Dictionary<MyEnum, string>()
        {
            { MyEnum.One, "do something with one" },
            { MyEnum.Two, "do something with two" },
        };

        [EnumeratedValueArgument(typeof(string), 'm', "myEnum", AllowedValues = string.Join(";", EnumMapping.Keys)]
        public string ParsedEnum;
```

but that gives:

> An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

any ideas on this sort of functionality?

**Comment by j-maly** [comment]
EnumeratedValueArgument is not the best here. It is meant for cases where you have a known set of primitive values you want to allow. E.g. 1,2,3,4,5,6

You can use plain ValueArgument:
```csharp
ValueArgument<MyEnum> //(in code) 
```
or 
```csharp
[ValueArgument(typeof(MyEnum),...)] //(in attributes)
```

it should work fine for you

**Comment by Kritner** [comment]
Darn, guess no method for grabbing the list of valid values from the enum using that attribute either eh?
