### ISSUE TITLE
v3.0.20 binary is not signed

### ISSUE THREAD

**Issue by TheSaltyKorean** [j-maly/CommandLineParser#67]
'warning BC41997: Referenced assembly 'CommandLineArgumentsParser, Version=3.0.20.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.'

Not sure what happened but the binary isn't signed again

**Comment by TheSaltyKorean** [comment]
Looks like the last version that was signed was version 3.0.16

**Comment by StefH** [comment]
@j-maly It seems the pfx file is password protected, so cannot create a new build. Do you have the password? If so, can you share? Or just create version 3.0.21?

**Comment by TheSaltyKorean** [comment]
bump ...
We should be able to create a new signing file.  An snk file will do just fine.  The public nature of the file/password is rather meaningless as even Microsoft hopes to do away with signing files.  The problem comes in when software publishers like me need signed files in order for applications to work on corporate desktops due to policy restrictions

**Comment by StefH** [comment]
I can just add a snk file to git and just create a `signed` dll.

Not 100% secure/preferred but this will work.

**Comment by alexandre-lecoq** [comment]
If you can add a snk file that would be great.
Lot of projects do that : https://github.com/commandlineparser/commandline/blob/master/CommandLine.snk

**Comment by askids** [comment]
Any plans of addressing this in near term?

**Comment by StefH** [comment]
Hello @j-maly , is it ok that I create a new signed NuGet with a new `snk` file?

**Comment by askids** [comment]
@StefH any plans to publish the new version using new snk file?

**Comment by StefH** [comment]
Hello @askids, a new version will be added to NuGet shortly.

https://github.com/j-maly/CommandLineParser/pull/72

**Comment by askids** [comment]
Thank you @StefH
