### ISSUE TITLE
RegexValueArgumentAttribute(char shortName, string longName, string pattern) constructor declaration error

### ISSUE THREAD

**Issue by dmagician038** [j-maly/CommandLineParser#79]
Assigning value to _argumentType causing exception:

> System.Reflection.TargetException
>   HResult=0x80131603
>   Message=Object does not match target type.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
>    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
>    at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
>    at ShutDown.CommandLineParser.TypeExtensions.SetPropertyValue(Type type, String propertyName, Object target, Object value) in ...\src\CommandLineArgumentsParser\Arguments\TypeExtensions.cs:line 58
> 
>   This exception was originally thrown at this call stack:
>     ShutDown.CommandLineParser.TypeExtensions.SetPropertyValue(System.Type, string, object, object) in TypeExtensions.cs
> 

assignment of _argumentType should be **RegexValueArgument** and not RegexValueArgumentAttribute.

**Comment by StefH** [comment]
@dmagician038 
Can you please provide a full working example (console app)?

**Comment by dmagician038** [comment]
Attached a basic project.

[console app.zip](https://github.com/j-maly/CommandLineParser/files/9259076/test.zip)

1. The 1st test **_Test1()_** is working OK.
2. The 2nd test **_Test2()_** is throwing exception.

BTW, I've fixed it on copied code from your repo - as described in my OP

**Comment by StefH** [comment]
https://github.com/j-maly/CommandLineParser/pull/80

**Comment by StefH** [comment]
Hello @dmagician038, this issue is fixed, I'll release a new NuGet soon.

**Comment by dmagician038** [comment]
Thank you!
